- name: Uninstall NGINX
  hosts: all
  become: true
  tasks:
    - name: Stop nginx service
      service: 
        name: nginx
        state: stopped
        enabled: no

    - name: Sterge nginx package
      apt:
        name: nginx
        state: absent

    - name: Remove nginx config pentru toate librariile ce incep cu nginx
      apt:
        name: nginx*
        state: absent
        purge: yes

    - name: Sterge toate dependintele ce nu mai sunt folosite
      apt:
        autoremove: yes