[frontend]
app1 ansible_host=192.168.2.188 ansible_user=ansible 
# ansible_ssh_private_key_file=/home/ansible/.ssh/ansible-ssh-key
app2 ansible_host=192.168.2.192 ansible_user=ansible 
# ansible_ssh_private_key_file=/home/ansible/.ssh/ansible-ssh-key

[database]
db1 ansible_host=192.168.2.194 ansible_user=ansible ansible_port=2200 
# ansible_ssh_private_key_file=/home/ansible/.ssh/ansible-ssh-key

[all_servers:children] 
frontend
database

[remote:children] 
frontend
database

[all:vars]
ansible_python_interpreter=/usr/bin/python3